version: '3.4'

services:
   catalogDb:
      container_name: catalogDb
      environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRRS_DB=catalogDb
      restart: always
      ports:
       - "5432:5432"
      volumes:
       - postgres_catalog:/var/lib/postgresql/data 